#!/bin/sh

# echo "--- Normalizing and updating production names in Regular..."
# psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/masters/BJCree-Regular.ufo

echo "--- Updating glyph orders in Regular..."
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/masters/BJCree-Regular.ufo

echo "--- Normalizing Regular..."
psfnormalize -p scrlevel=w -p checkfix=fix source/masters/BJCree-Regular.ufo
echo "--- Normalizing Bold..."
psfnormalize -p scrlevel=w -p checkfix=fix source/masters/BJCree-Bold.ufo

echo "--- Rebuilding composites..."
psfbuildcomp -p backup=False --force --noflatten --colors="leave,g_purple,g_red" \
    -i source/composites.txt source/masters/BJCree-Regular.ufo
psfbuildcomp -p backup=False --force --noflatten --colors="leave,g_purple,g_red" \
    -i source/composites.txt source/masters/BJCree-Bold.ufo

echo "--- Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -p scrlevel=w source/BJCree.designspace

# echo "--- Updating WOFF metadata..."
# psfmakewoffmetadata -p scrlevel=w -n "BJCree" -i "org.sil.fonts" \
#     -o source/BJCree-WOFF-metadata.xml \
#     source/masters/BJCree-Regular.ufo
# psfmakewoffmetadata -p scrlevel=w -n "BJCree" -i "org.sil.fonts" \
#     -o source/BJCree-WOFF-metadata.xml \
#     source/masters/BJCree-Bold.ufo
