#!/bin/sh

# echo "--- Normalizing and updating production names in Regular..."
# psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/masters/BJCree-Regular.ufo

# echo "--- Updating glyph orders in Regular..."
# psfsetglyphorder --header sort_design -i source/glyph_data.csv source/masters/BJCree-Regular.ufo

echo "--- Normalizing Regular..."
psfnormalize -p scrlevel=w -p checkfix=fix source/masters/BJCree-Regular.ufo
echo "--- Normalizing Bold..."
psfnormalize -p scrlevel=w -p checkfix=fix source/masters/BJCree-Bold.ufo

# echo "--- Rebuilding composites..."
# psfbuildcomp -i source/composites.txt --colors="g_blue,g_purple" -n source/masters/BJCree-Regular.ufo -p backup=False
# psfbuildcomp -i source/composites.txt --colors="g_blue,g_purple" -n source/masters/BJCree-Bold.ufo -p backup=False

# echo "--- Syncing glyph orders, psnames, and other metadata to other UFOs..."
# psfsyncmasters source/BJCree.designspace

# echo "--- Updating WOFF metadata..."
# psfmakewoffmetadata -n "BJCree" -i "org.sil.fonts" -o source/BJCree-WOFF-metadata.xml source/masters/BJCree-Regular.ufo
